#!/usr/bin/env python3
"""
Run PSD (with Depth Pro backend) on undistorted COLMAP images and write COLMAP photometric depth bins.

Pipeline
- Assumes COLMAP image_undistorter has produced <dense_dir>/images and <dense_dir>/sparse (TXT) with cameras/images.
- Uses sparse depth PNGs generated by scripts/depth_pro/colmap_sparse_to_sparse_depth.py and reads intrinsics from its CSV.
- For each image, runs PSD single-image inference guided by sparse depth and intrinsics, then writes
  <dense_dir>/stereo/depth_maps/<relname>.photometric.bin (HxW float32 meters with COLMAP MatBin header "w&h&1&").

Notes
- Always use undistorted images (<dense_dir>/images) and intrinsics from the undistorted sparse model.
- This script intentionally avoids extra defensive rescaling/fallbacks; it trusts PSD output and lets COLMAP stereo_fusion filter.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image


# Repo roots for imports
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PSD_ROOT = os.path.join(REPO_ROOT, "third_party", "PSD")
for p in (PSD_ROOT, REPO_ROOT):
    if p not in sys.path:
        sys.path.insert(0, p)

# PSD network and a lightweight fill-in util
from network.ipde_5c_l1_rezero_un_3 import DCNet  # type: ignore
import importlib.util as _importlib_util  # type: ignore
_ip_basic_path = os.path.join(PSD_ROOT, "datasets", "ip_basic.py")
_spec = _importlib_util.spec_from_file_location("psd_ip_basic", _ip_basic_path)
_ip_basic = _importlib_util.module_from_spec(_spec)
assert _spec and _spec.loader is not None
_spec.loader.exec_module(_ip_basic)  # type: ignore[attr-defined]
ip_fill = _ip_basic.fill_in_fast


def write_colmap_mat_bin(path: Path, arr: np.ndarray) -> None:
    # Accept HxW or HxWxC float32 arrays (COLMAP MatBin)
    if arr.ndim == 2:
        h, w = arr.shape
        c = 1
    elif arr.ndim == 3:
        h, w, c = arr.shape
    else:
        raise ValueError("Expected 2D or 3D array")
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "wb") as f:
        f.write(f"{w}&{h}&{c}&".encode("ascii"))
        arr.astype(np.float32).tofile(f)


def compute_normals_from_depth(depth: np.ndarray, fx: float, fy: float, cx: float, cy: float) -> np.ndarray:
    # depth: HxW float32 meters; returns HxWx3 normals (camera frame)
    h, w = depth.shape
    uu = np.arange(w, dtype=np.float32)[None, :].repeat(h, axis=0)
    vv = np.arange(h, dtype=np.float32)[:, None].repeat(w, axis=1)
    Z = depth.astype(np.float32)
    X = (uu - cx) * Z / (fx if fx != 0 else 1e-6)
    Y = (vv - cy) * Z / (fy if fy != 0 else 1e-6)
    dXu = X[:, 1:] - X[:, :-1]
    dYu = Y[:, 1:] - Y[:, :-1]
    dZu = Z[:, 1:] - Z[:, :-1]
    dXv = X[1:, :] - X[:-1, :]
    dYv = Y[1:, :] - Y[:-1, :]
    dZv = Z[1:, :] - Z[:-1, :]
    ax = np.stack([dXu[:-1, :], dYu[:-1, :], dZu[:-1, :]], axis=2)
    ay = np.stack([dXv[:, :-1], dYv[:, :-1], dZv[:, :-1]], axis=2)
    # Orient like COLMAP PatchMatch (camera-facing normals): use ay x ax so Nz<=0
    n = np.cross(ay, ax)
    norm = np.linalg.norm(n, axis=2, keepdims=True)
    norm = np.maximum(norm, 1e-8)
    n = n / norm
    normals = np.zeros((h, w, 3), dtype=np.float32)
    normals[:-1, :-1, :] = n.astype(np.float32)
    normals[-1, :-1, :] = normals[-2, :-1, :]
    normals[:-1, -1, :] = normals[:-1, -2, :]
    normals[-1, -1, :] = normals[-2, -2, :]
    invalid = ~np.isfinite(Z) | (Z <= 0)
    normals[invalid] = 0.0
    # Enforce Nz<=0 convention where valid
    valid = ~invalid
    flip = valid & (normals[..., 2] > 0)
    normals[flip] *= -1.0
    return normals


def load_rgb(path: str) -> torch.Tensor:
    im = Image.open(path).convert("RGB")
    arr = np.asarray(im, dtype=np.uint8)
    ten = torch.from_numpy(arr).permute(2, 0, 1).unsqueeze(0).float() / 255.0
    return ten


def to_normalized(rgb: torch.Tensor) -> torch.Tensor:
    mean = torch.tensor([0.5, 0.5, 0.5], dtype=rgb.dtype, device=rgb.device).view(1, 3, 1, 1)
    std = torch.tensor([0.5, 0.5, 0.5], dtype=rgb.dtype, device=rgb.device).view(1, 3, 1, 1)
    return (rgb - mean) / std


def load_sparse_depth_png(path: str, target_hw: Optional[tuple[int, int]] = None, scale_divisor: float = 256.0) -> torch.Tensor:
    img = Image.open(path)
    arr = np.array(img, dtype=np.int32)
    depth = arr.astype(np.float32) / float(scale_divisor)
    depth[depth <= 0] = 0.0
    depth_t = torch.from_numpy(depth).unsqueeze(0).unsqueeze(0)  # 1,1,H,W
    if target_hw is not None:
        depth_t = F.interpolate(depth_t, size=target_hw, mode="nearest")
    return depth_t


def build_cfg(cfg_path: str, depthpro_ckpt: str):
    from omegaconf import OmegaConf  # lazy import
    cfg = OmegaConf.load(cfg_path)
    cfg.MDEBranch.backbone = "depthpro"
    cfg.MDEBranch["depthpro"] = {
        "pretrained": depthpro_ckpt,
        "resize_h": 384,
        "resize_w": 384,
        "mean": [0.5, 0.5, 0.5],
        "std": [0.5, 0.5, 0.5],
    }
    if "RegressBranch" in cfg and "resnet" in cfg.RegressBranch:
        cfg.RegressBranch.resnet.pretrained = None
    if "CSLBranch" in cfg and "resnet" in cfg.CSLBranch:
        cfg.CSLBranch.resnet.pretrained = None
    return cfg


def robust_load_state_dict(model: torch.nn.Module, ckpt_path: str) -> None:
    try:
        state = torch.load(ckpt_path, map_location="cpu")
    except Exception as e:  # noqa: BLE001
        import warnings
        warnings.warn(f"Safe load failed ({e}); retrying with weights_only=False.")
        state = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    if isinstance(state, dict) and "model" in state:
        state_dict = state["model"]
    else:
        state_dict = state
    new_state = {}
    for k, v in state_dict.items():
        nk = k[7:] if k.startswith("module.") else k
        new_state[nk] = v
    model.load_state_dict(new_state, strict=False)


def read_intrinsics_csv(csv_path: Path) -> Dict[str, Dict[str, float]]:
    table: Dict[str, Dict[str, float]] = {}
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row["image"]
            try:
                table[name] = {
                    "fx": float(row.get("fx", 0.0)),
                    "fy": float(row.get("fy", 0.0)),
                    "cx": float(row.get("cx", 0.0)),
                    "cy": float(row.get("cy", 0.0)),
                    "w": float(row.get("width", 0)),
                    "h": float(row.get("height", 0)),
                }
            except Exception:
                continue
    return table


def main() -> int:
    ap = argparse.ArgumentParser(description="PSD inference on undistorted images -> COLMAP depth bins")
    default_cfg = os.path.join(PSD_ROOT, "configs", "cfg.yml")
    ap.add_argument("--dense_dir", required=True, help="Path to <run>/dense")
    ap.add_argument("--sparse_png_dir", required=True, help="Path to sparse depth PNG root (mirrors image names)")
    ap.add_argument("--intrinsics_csv", default=None, help="CSV with columns: image,fx,fy,cx,cy,width,height")
    ap.add_argument("--psd_ckpt", default="PSD_NK_DPr_checkpoint.ckpt", help="PSD weights (.ckpt/.pth)")
    ap.add_argument("--depthpro_ckpt", default="third_party/ml-depth-pro/checkpoints/depth_pro.pt", help="Depth Pro weights (.pt)")
    ap.add_argument("--cfg", default=default_cfg, help="PSD base cfg YAML")
    ap.add_argument("--sparse_scale", type=float, default=256.0, help="Divisor used to encode sparse PNGs")
    ap.add_argument("--data", type=str, default="KITTI", help="Dataset profile for PSD (e.g., KITTI/NYUv2)")
    ap.add_argument("--list", default=None, help="Optional path to an image list to filter (compares by basename)")
    args = ap.parse_args()

    dense = Path(args.dense_dir)
    undist_imgs = dense / "images"
    out_dir = dense / "stereo" / "depth_maps"
    sparse_png_root = Path(args.sparse_png_dir)
    intr_csv = Path(args.intrinsics_csv) if args.intrinsics_csv else (sparse_png_root / "intrinsics.csv")

    if not undist_imgs.exists():
        print(f"[error] images folder not found: {undist_imgs}")
        return 2
    if not intr_csv.exists():
        print(f"[error] intrinsics CSV not found: {intr_csv}")
        return 2

    name2intr = read_intrinsics_csv(intr_csv)
    if not name2intr:
        print(f"[error] intrinsics CSV empty or invalid: {intr_csv}")
        return 2

    # Build model once
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cfg = build_cfg(args.cfg, args.depthpro_ckpt)
    # Reduce KNN rate to be safe on memory for single-image inference
    ds_name = args.data
    if ds_name in cfg and hasattr(cfg[ds_name], "knn_rate"):
        try:
            cfg[ds_name].knn_rate = float(min(float(cfg[ds_name].knn_rate), 0.05))
        except Exception:
            cfg[ds_name].knn_rate = 0.05

    net = DCNet(cfg).to(device).eval()
    robust_load_state_dict(net, args.psd_ckpt)

    # Optional filter list: compare by basename for convenience
    sel: Optional[set[str]] = None
    if args.list and Path(args.list).exists():
        with open(args.list, "r", encoding="utf-8") as f:
            sel = {Path(l.strip()).name for l in f if l.strip()}

    # Gather all images (support nested subfolders)
    img_paths: list[Path] = sorted([p for p in undist_imgs.rglob("*") if p.is_file()])
    if not img_paths:
        print(f"[error] No images found under {undist_imgs}")
        return 2

    written = 0
    for p in img_paths:
        name_rel: str
        try:
            name_rel = str(p.relative_to(undist_imgs))
        except Exception:
            name_rel = p.name

        if sel and p.name not in sel:
            continue
        intr = name2intr.get(name_rel)
        if intr is None:
            # Try with just basename fallback if CSV used different path style
            intr = name2intr.get(p.name)
            if intr is None:
                print(f"[warn] intrinsics not found for {name_rel}; skip")
                continue

        # Paths to sparse depth
        sparse_png = sparse_png_root / Path(name_rel).with_suffix(".png")
        if not sparse_png.exists():
            # Allow basename fallback
            alt = sparse_png_root / (p.stem + ".png")
            if alt.exists():
                sparse_png = alt
            else:
                print(f"[warn] sparse PNG missing for {name_rel}: {sparse_png}")
                continue

        # Load inputs
        rgb = load_rgb(str(p)).to(device)
        H, W = int(rgb.shape[2]), int(rgb.shape[3])
        rgb_norm = to_normalized(rgb)
        sparse = load_sparse_depth_png(str(sparse_png), target_hw=(H, W), scale_divisor=args.sparse_scale).to(device)

        # Fast fill-in to provide ip prior
        sparse_np = sparse.detach().cpu().numpy().squeeze()
        ip_np = ip_fill(sparse_np, max_depth=float(np.max(sparse_np)) if np.max(sparse_np) > 0 else 1.0)
        ip_tensor = torch.from_numpy(ip_np).unsqueeze(0).unsqueeze(0).to(device)

        # Depth Pro branch expects 384x384 normalized
        rgb_for_mde = torch.nn.functional.interpolate(rgb, size=(384, 384), mode="bilinear", align_corners=False)
        rgb_for_mde = to_normalized(rgb_for_mde)

        # Intrinsics to tensor
        fx = float(intr.get("fx", 0.0)) or (W / 2.0)
        fy = float(intr.get("fy", 0.0)) or (H / 2.0)
        cx = float(intr.get("cx", 0.0)) or (W / 2.0)
        cy = float(intr.get("cy", 0.0)) or (H / 2.0)
        K = torch.tensor([[fx, 0.0, cx], [0.0, fy, cy], [0.0, 0.0, 1.0]], dtype=torch.float32, device=device).unsqueeze(0)

        inputs = {
            "rgb": rgb_norm,
            "rgb_s": rgb,
            "rgb_mde": rgb_for_mde,
            "sparse": sparse,
            "ip": ip_tensor,
            "K": K,
        }

        with torch.no_grad():
            outputs = net(inputs, epoch=42, is_test=True, data=args.data)
            depth_list = outputs.get("depth")
            if isinstance(depth_list, (list, tuple)):
                pred_depth = depth_list[-1]
            else:
                pred_depth = depth_list

        depth_np = pred_depth.detach().float().cpu().squeeze(0).squeeze(0).numpy()
        depth_np[~np.isfinite(depth_np)] = 0.0
        depth_np[depth_np <= 0.0] = 0.0

        # Write depth as COLMAP photometric bin
        out_path = out_dir / f"{name_rel}.photometric.bin"
        write_colmap_mat_bin(out_path, depth_np.astype(np.float32))
        # Also write normal map to satisfy COLMAP stereo_fusion expectations in photometric mode
        normal_dir = dense / "stereo" / "normal_maps"
        normals = compute_normals_from_depth(depth_np.astype(np.float32), fx, fy, cx, cy)
        write_colmap_mat_bin(normal_dir / f"{name_rel}.photometric.bin", normals)
        print(f"[ok] wrote {out_path} and normals")
        written += 1

        # Free per-image activations
        del inputs, pred_depth, depth_np
        if device.type == "cuda":
            torch.cuda.empty_cache()

    print(f"[done] Wrote {written} COLMAP photometric depth bins under {out_dir}")
    return 0 if written > 0 else 3


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
